name = "HodgkinModel"
uuid = "c52538b9-1f76-4f98-a2c7-6d5a25f501a3"
authors = ["Ahmed Almijbari <ahmed.elmagbri@gmail.com>"]
version = "0.1.0"

[deps]
DiffEqFlux = "aae7a2af-3d4f-5e19-a356-7da93b79d9d0"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Flux = "0.13"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
